server:
  port: 9054

spring:
  ##쿼리 및 테이블 생성을 보기 위한 설정
  jpa:
    ##만들어지는 SQL 보여줌
    show-sql: true
    properties:
      hibernate:
        ## 쿼리가 보기 쉬운 형태로 바꿔줌
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  ##테이블 생성방식을 어떻게 결정할지 설정
  hibernate:
    ddl-auto: create-drop


  ##h2를 연결하기 위한 설정
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/userjpa
    username: sa